parameters:
    env(WKHTMLTOPDF_PATH): 'vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
    env(WKHTMLTOIMAGE_PATH): '/usr/local/bin/wkhtmltoimage'

knp_snappy:
    pdf:
        enabled:    true
        binary:     '%kernel.project_dir%/vendor/bin/wkhtmltopdf-amd64'
        options:
            page-size: A4
            dpi: 300
            margin-left: 15mm
            margin-right: 15mm
            margin-top: 15mm
            margin-bottom: 15mm
            user-style-sheet: '%kernel.root_dir%/../public/build/app.css'
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
